import org.jetbrains.intellij.platform.gradle.TestFrameworkType
import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType
import org.gradle.process.CommandLineArgumentProvider

plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.intellij.platform")
    id("org.jetbrains.changelog")
}

kotlin {
    jvmToolchain(21)
}

// ADR 0002 D6: the Grammar-Kit Gradle plugin is not used. The lexer is generated by
// invoking the IntelliJ-patched JFlex jar directly from a JavaExec task, kept
// configuration-cache compatible via argumentProviders (see docs/adr/0002).
val jflex: Configuration by configurations.creating

val generateTypeSpecLexer by tasks.registering(JavaExec::class) {
    val flexFile = layout.projectDirectory.file("src/main/grammars/_TypeSpecLexer.flex")
    val outDir = layout.buildDirectory.dir("generated/sources/jflex/dev/tsp/intellij/typespec/lexer")
    inputs.file(flexFile)
    outputs.dir(outDir)
    classpath = jflex
    mainClass = "jflex.Main"
    argumentProviders.add(CommandLineArgumentProvider {
        listOf("-d", outDir.get().asFile.absolutePath, "--nobak", flexFile.asFile.absolutePath)
    })
    doFirst {
        outDir.get().asFile.mkdirs()
    }
}

sourceSets {
    main {
        java.srcDir(generateTypeSpecLexer.map { layout.buildDirectory.dir("generated/sources/jflex") })
    }
}

tasks.named("compileKotlin") {
    dependsOn(generateTypeSpecLexer)
}

dependencies {
    testImplementation("junit:junit:4.13.2")

    jflex("org.jetbrains.intellij.deps.jflex:jflex:1.10.17")

    // IntelliJ Platform Gradle Plugin Dependencies Extension - read more: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-dependencies-extension.html
    intellijPlatform {
        // ADR 0002 D1: intellijIdeaCommunity() is deprecated by the Gradle plugin in favour
        // of intellijIdea(), which resolves the unified IU-coded distribution starting at
        // 2025.3. We intentionally keep using the deprecated Community-only helper here: it
        // is the only way to get a compile classpath that physically lacks Ultimate classes,
        // which is the enforcement mechanism for this project's CE-only constraint. Do not
        // "fix" this deprecation warning. See docs/adr/0002-build-and-platform-baseline.md.
        @Suppress("DEPRECATION")
        intellijIdeaCommunity("2025.2.6.3")
        testFramework(TestFrameworkType.Platform)
    }
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild = "252"
            untilBuild = provider { null }
        }
    }

    pluginVerification {
        ides {
            create(IntelliJPlatformType.IntellijIdeaCommunity, "2025.2.6.3")
        }
    }
}

