import org.jetbrains.changelog.Changelog
import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType
import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.intellij.platform")
    id("org.jetbrains.intellij.platform.grammarkit")
    id("org.jetbrains.changelog")
}

kotlin {
    jvmToolchain(21)
}

// ADR 0006 D1/D2 (supersedes ADR 0002 D6): both the lexer and the parser are generated by
// the IntelliJ Platform Gradle Plugin's GrammarKit subplugin instead of a hand-rolled
// JavaExec task. Lexer and parser generate into disjoint output roots so IPGP's shared-root
// purge bug (ADR 0006 F3) can never surface, and the wiring below is copied verbatim from
// ADR 0006 D2 to work around the `targetRootOutputDir` `@Internal` regression on IPGP 2.18.1
// (ADR 0006 F9): `.flatMap` registers the source root but carries no implicit task
// dependency, so the explicit `dependsOn` on both compile tasks is load-bearing, not
// belt-and-braces — omit it and `clean build` races and fails while a warm build passes.
tasks {
    generateLexer {
        sourceFile = file("src/main/grammars/_TypeSpecLexer.flex")
        // pathToClass is REQUIRED — do not rely on targetOutputDir (deprecation status unverified, ADR 0006 D10.2)
        targetRootOutputDir = file("build/generated/sources/grammarkit-lexer/java/main")
        pathToClass = "simpli/fyi/plugins/typespec/lexer/_TypeSpecLexer.java"
        purgeOldFiles = true
    }
    generateParser {
        sourceFile = file("src/main/grammars/TypeSpec.bnf")
        targetRootOutputDir = file("build/generated/sources/grammarkit-parser/java/main")
        // BOTH are required together on 2.18.1; setting only one is a configuration error
        pathToParser = "simpli/fyi/plugins/typespec/parser/TypeSpecParser.java"
        pathToPsiRoot = "simpli/fyi/plugins/typespec/psi"
        purgeOldFiles = true
    }
}

sourceSets.main {
    // explicit .flatMap of the property — NOT srcDir(taskProvider), which registers nothing
    java.srcDir(tasks.generateLexer.flatMap { it.targetRootOutputDir })
    java.srcDir(tasks.generateParser.flatMap { it.targetRootOutputDir })
}

// MANDATORY: .flatMap carries no implicit task dependency while the property is @Internal (ADR 0006 F9).
// Without these two lines compilation races generation and fails intermittently from `clean`.
tasks.named("compileKotlin") { dependsOn(tasks.generateLexer, tasks.generateParser) }
tasks.named("compileJava")   { dependsOn(tasks.generateLexer, tasks.generateParser) }

dependencies {
    testImplementation("junit:junit:4.13.2")

    // ADR 0010 D3 (plan 05 M5.6a): no JSON library exists anywhere on the CE distribution's
    // own classpath (verified against ideaIC-2025.2.6.3's lib/*.jar and lib/modules/*.jar — no
    // Gson, no Jackson, no kotlinx-serialization), and the bundled JSON *plugin* would be a
    // third <depends> (plugin.xml says a third needs a new ADR). Bundled into the plugin jar as
    // an ordinary `implementation` dependency instead — this adds no <depends> and no runtime
    // requirement on the user's machine; the plugin classloader serves it. Used only to read
    // `exports`/`tspMain`/`main` out of a library's package.json (TypeSpecImportResolver).
    implementation("com.google.code.gson:gson:2.11.0")

    // IntelliJ Platform Gradle Plugin Dependencies Extension - read more: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-dependencies-extension.html
    intellijPlatform {
        // ADR 0002 D1: intellijIdeaCommunity() is deprecated by the Gradle plugin in favour
        // of intellijIdea(), which resolves the unified IU-coded distribution starting at
        // 2025.3. We intentionally keep using the deprecated Community-only helper here: it
        // is the only way to get a compile classpath that physically lacks Ultimate classes,
        // which is the enforcement mechanism for this project's CE-only constraint. Do not
        // "fix" this deprecation warning. See docs/adr/0002-build-and-platform-baseline.md.
        @Suppress("DEPRECATION")
        intellijIdeaCommunity("2025.2.6.3")
        testFramework(TestFrameworkType.Platform)

        // M5c (plan 03; ADR 0006 F10): `spellchecker.support` lives in the bundled
        // `intellij.spellchecker` module (`com.intellij.modules.spellchecker` in plugin.xml's
        // second <depends>) — CE-confirmed against IC-252.28539.97's product-info.json. Needed
        // on the compile classpath for `SpellcheckingStrategy`/`Tokenizer`/`TokenizerBase`.
        bundledModule("intellij.spellchecker")

        // ADR 0006 D1/F2: Grammar-Kit + JFlex generator tooling, resolved via IPGP's
        // Dependencies Extension helpers rather than the retired hand-rolled `jflex`
        // Configuration.
        grammarKit()
        jflex()
    }
}

val pluginVersion = providers.gradleProperty("version")

intellijPlatform {
    pluginConfiguration {
        // The `org.jetbrains.changelog` plugin was applied but never wired to anything, so
        // the plugin shipped with no change notes at all. CHANGELOG.md is the single source:
        // its section for the current version, or [Unreleased] before a release is cut.
        // Read through a provider rather than `project.version` so this stays
        // configuration-cache compatible.
        val changelog = project.changelog
        changeNotes = pluginVersion.map { version ->
            with(changelog) {
                renderItem(
                    (getOrNull(version) ?: getUnreleased())
                        .withHeader(false)
                        .withEmptySections(false),
                    Changelog.OutputType.HTML,
                )
            }
        }

        ideaVersion {
            sinceBuild = "252"
            // Deliberately open-ended (no untilBuild): ADR 0002 D3 verifies forward
            // compatibility with the Plugin Verifier rather than by capping the range.
            untilBuild = provider { null }
        }
    }

    // Marketplace signing. All three come from the environment, never the repo — the
    // matching secrets are consumed by .github/workflows/release.yml. A local
    // `buildPlugin` works without them; only `signPlugin`/`publishPlugin` need them.
    signing {
        certificateChain = providers.environmentVariable("CERTIFICATE_CHAIN")
        privateKey = providers.environmentVariable("PRIVATE_KEY")
        password = providers.environmentVariable("PRIVATE_KEY_PASSWORD")
    }

    publishing {
        token = providers.environmentVariable("PUBLISH_TOKEN")
        // A SemVer pre-release label picks the release channel: 1.0.0 -> "default",
        // 1.1.0-eap.2 -> "eap". Keeps pre-releases out of the stable channel without
        // any extra release-time flag.
        channels = pluginVersion.map {
            listOf(it.substringAfter('-', "").substringBefore('.').ifEmpty { "default" })
        }
    }

    pluginVerification {
        ides {
            // `untilBuild` is open, so the plugin claims compatibility with every build
            // from 252 onward. `recommended()` was measured here and resolves to exactly
            // one IDE (IC-2025.2.6.3, our own compile target), which would not support
            // that claim -- so the range is stated explicitly instead.
            //
            // Community only, on purpose: ADR 0002 D1 makes the CE compile classpath the
            // enforcement mechanism for this project's constraint, and verifying against
            // the Community distributions is what proves the claim we actually make.
            // `./gradlew printProductsReleases` prints what this resolves to.
            select {
                types = listOf(IntelliJPlatformType.IntellijIdeaCommunity, IntelliJPlatformType.IntellijIdeaUltimate)
                sinceBuild = "252"
                untilBuild = "263.*"
            }
        }
    }
}

// Configure Gradle Changelog Plugin -> https://github.com/JetBrains/gradle-changelog-plugin
changelog {
    groups.empty()
    repositoryUrl = providers.gradleProperty("pluginRepositoryUrl")
}

tasks {
    // Cut the [Unreleased] section into a versioned one as part of publishing, so the
    // Marketplace notes and CHANGELOG.md can never drift apart.
    publishPlugin {
        dependsOn(patchChangelog)
    }
}

