// (comment)
// (comment)
// (comment)
// (comment)
// (comment)
// (comment)
// (comment)
// (comment)
// (comment)
// (comment)
// (comment)

import "@typespec/protobuf";
import "../../common/lagoon.tsp";
import "../../common/bravo/mike.tsp";
import "../../common/signals/payloaddata-umber-jade.tsp";
import "../booking.tsp";
import "../signals/signals.tsp";
import "../signals/group.tsp";

using TypeSpec.Protobuf;

@@package(Acme.Ex.Core.Booking, { name: "acme.ex.core.booking" });
